### ISSUE TITLE
Reset email not working

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#209]
![captura de tela 2016-02-06 as 11 19 03](https://cloud.githubusercontent.com/assets/28031/12866372/7e01defc-ccc3-11e5-8054-35aed12b0be3.png)

**Comment by dborkan** [comment]
I was getting this error on my local setup as well.  The problem is that Gmail doesn't trust the way we are programmatically sending email, explained a bit more in https://support.google.com/accounts/answer/78754.

Using a test account as the email address in the config json files, I was able to get this working by going to https://myaccount.google.com/security and setting "Allow less secure apps" to ON.  I'm trying to find out more about what the risks are in doing this, but it sounds scary so I wouldn't recommend using it on anything other than a test account (we should probably have a unique account for Copcast emails anyways).

I believe the correct way to send email from a Gmail address is to use OAuth, which nodemailer seems to support (see 2nd answer on http://stackoverflow.com/questions/19877246/nodemailer-with-gmail-and-nodejs).  We would need to get a refresh_token (and then use that to get an access_token) for the account we want the email sent from.

**Comment by dborkan** [comment]
Actually the slightly easier and secure way to do this is to create an application specific password, instructions at https://security.google.com/settings/security/apppasswords.  This requires two-factor authentication to be setup, but that's a good idea to have anyways.
