### ISSUE TITLE
Fit all officers button in map

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#238]
We have defined a button to fit all markers in the map in case the admin user have navigated (zoomed in/out...) a lot.
Use the mock below as a model, but replace it with the text "All Officers"
![screen shot 2016-04-26 at 18 33 08](https://cloud.githubusercontent.com/assets/28031/14853257/ab964de0-0c82-11e6-94e4-64c6ceb570da.png)

**Comment by arthurvasconcelos** [comment]
In commit dfc68b469dd780d7ae374c771bfce2cf4be14fb7 I needed to change the positioning of the button because some extra information in Google Maps buttons.

![Map Button](http://i.imgur.com/NkHvxqb.png) ![Satellite Button](http://i.imgur.com/0QyMHFd.png)

I used the Google Maps buttons "active" style in our button to show when we are fetching data.

![Active Fetching Data](http://i.imgur.com/QFS2DLJ.png)
