### ISSUE TITLE
socketHandler possible bug

### ISSUE THREAD

**Issue by fcavalcantirj** [igarape/copcast-admin#95]
ReferenceError: next is not defined
    at /home/mogi/mogi-server/lib/streams/socketHandler.js:28:27
    at Object.validateBearerToken [as validateToken] (/home/mogi/mogi-server/lib/auth/index.js:46:12)

**Comment by brunosiqueira** [comment]
the problem was with the android socket client. It was sending the token in the wrong variable. In the authentication method (io.use) it was getting rejected, but the next method was receiving the wrong arguments, so it wasn't identifying properly the rejection.

And in the io.on('connection'), there was no next method. So now it just returns null to stop the creation of the methods
